from concurrent import futures
import os

import grpc
from prometheus_client import Counter, start_http_server

from proto.generated import alarm_pb2, alarm_pb2_grpc

from .db import init_db
from .rules import evaluate_alarms
from .storage import save_alarm_events


RECORDS_EVALUATED_TOTAL = Counter(
    "alarm_records_evaluated_total",
    "Total normalized records evaluated by the alarm service.",
)
ALARM_EVENTS_GENERATED_TOTAL = Counter(
    "alarm_events_generated_total",
    "Total alarm events generated by the alarm service.",
)
ALARM_PERSISTENCE_ERRORS_TOTAL = Counter(
    "alarm_persistence_errors_total",
    "Total alarm persistence errors in the alarm service.",
)
ALARM_EVENTS_BY_CODE_TOTAL = Counter(
    "alarm_events_by_code_total",
    "Total alarm events generated by alarm code and severity.",
    ["code", "severity"],
)


class AlarmGrpcService(alarm_pb2_grpc.AlarmServiceServicer):
    def EvaluateAlarms(self, request, context):
        alarms = evaluate_alarms(request)
        RECORDS_EVALUATED_TOTAL.inc()
        ALARM_EVENTS_GENERATED_TOTAL.inc(len(alarms))

        for alarm in alarms:
            ALARM_EVENTS_BY_CODE_TOTAL.labels(
                code=alarm.code,
                severity=alarm.severity,
            ).inc()

        try:
            save_alarm_events(request, alarms)
        except Exception:
            ALARM_PERSISTENCE_ERRORS_TOTAL.inc()
            raise

        return alarm_pb2.AlarmEvaluationResponse(
            source_id=request.source_id,
            alarm_count=len(alarms),
            alarms=alarms,
        )


def serve() -> None:
    init_db()
    port = os.getenv("ALARM_GRPC_PORT", "50052")
    metrics_port = int(os.getenv("ALARM_METRICS_PORT", "9102"))
    start_http_server(metrics_port)

    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    alarm_pb2_grpc.add_AlarmServiceServicer_to_server(
        AlarmGrpcService(),
        server,
    )
    server.add_insecure_port(f"[::]:{port}")
    server.start()
    print(f"Alarm gRPC server listening on port {port}")
    print(f"Alarm metrics server listening on port {metrics_port}")
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
